### ISSUE TITLE
credential helper

### ISSUE THREAD

**Issue by toppk** [aiokitchen/aiohttp-s3-client#18]
I wrote this so I can do aws creds the standard way with your library.  So instead of this:

```python
  async with ClientSession(raise_for_status=True) as session:
      client = S3Client(
          url="http://s3-url",
          session=session,
          access_key_id="key-id",
          secret_access_key="hackme",
          region="us-east-1"
      )
```

You can do this:

```python
  async with ClientSession(raise_for_status=True) as session:
      client = build_s3client(profile='auto', client=S3Client)(
          url="http://s3-url",
          session=session,
          )

```

and it retrieves the settings via standard aws env vars, config/cred files, or even the ec2metadata service.

Might be of use to your users who happen to be aws's s3 users as well.

gist is here, happy to license this in any way that would be helpful:

https://gist.github.com/toppk/f19403f663da4093d7abeb6159996820

**Comment by dizballanze** [comment]
Hi! Looks good, feel free to open a PR
