### ISSUE TITLE
aiohttp leaks connections and logs to stdout

### ISSUE THREAD

**Issue by toppk** [aiokitchen/aiohttp-s3-client#20]
Got this output:

```
Unclosed connection
client_connection: Connection<ConnectionKey(host='s3.amazonaws.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>
```

led me to this issue:
https://github.com/aio-libs/aiohttp/issues/5277

unfortunately, there really isn't much development happening on the client side of the aiohttp house, afaict.

I'm only using get/list_objects_v2, so for my usecase, I may just try to turn aiohttp-s3-client into a sans-io library.  have to give this some thought.  maybe I'll try shoving a httpx.session (my goto async client these days)  into aiohttp-s3-client and see where it breaks, looks like things like resp.status vs resp.status_code.

I'm thinking about just monkey patching this logging away from aiohttp, but digging into the aiohttp code makes me feel unsettled.

**Comment by toppk** [comment]
okay, I've spent some time thinking about this, and the name typing RequestContextManager gave me a clue. 

your examples in the README.md are not desirable. 

it should be either:

```python
    # Get object by bucket+key
    async with client.get("bucket/key") as resp:
        data = await resp.read()
```

or 
```python
    # Get object by bucket+key
    resp = await client.get("bucket/key")
    data = await resp.read()
    resp.release()  # must release
```
This covers all of your examples.

aiohttp documentation:
https://docs.aiohttp.org/en/stable/http_request_lifecycle.html

context manager implementation:
https://github.com/aio-libs/aiohttp/blob/v3.8.4/aiohttp/client.py#L1159

i'm a lot happier about aiohttp now :)

**Comment by mosquito** [comment]
@toppk do you want to fix examples or add mention about it?

**Comment by toppk** [comment]
~~yeah, I'll submit a PR later (maybe tomorrow).  I will~~ created PR to convert all the examples for `async with` style, as that matches the recommendations in aiohttp  and the least brittle.

**Comment by toppk** [comment]
This can be closed now.
