### ISSUE TITLE
Differentiate listing an empty prefix vs. an actual error.

### ISSUE THREAD

**Issue by rzvoncek** [aiokitchen/aiohttp-s3-client#25]
Hello,

When I [list objects](https://github.com/aiokitchen/aiohttp-s3-client/blob/master/aiohttp_s3_client/client.py#L746) on a prefix that does not exist, meaning there are no objects in the bucket, then I get an AwsDownloadError thrown.

I am finding this somewhat limiting. I'd need to tell if there has been an actual error, or if there simply are no objects.

Do you have any advice on how to handle this with the current implementation? Or do we need some sort of patch?

Thanks for any help in advance!

**Comment by mosquito** [comment]
After #22 (released as 0.9.3) it should be easer I hope.

**Comment by rzvoncek** [comment]
Understood. Once again, thanks for the help.
